# Decision tree и Random forest

Реализовать 2 класса DecisionTreeClassifier и RandomForestClassifier

In [1]:
class DecisionTreeClassifier():
    def __init__(self):
        pass
    def fit(self):
        pass
    def predict(self):
        pass
    def fit_predict(self):
        pass

In [2]:
class RandomForestClassifier():
    def __init__(self):
        pass
    def fit(self):
        pass
    def predict(self):
        pass
    def fit_predict(self):
        pass

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold


%matplotlib inline
df = pd.read_csv('./data/cs-training.csv', sep=',')
df.head()

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
1                 1                              0.766127   45   
2                 0                              0.957151   40   
3                 0                              0.658180   38   
4                 0                              0.233810   30   
5                 0                              0.907239   49   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
1                                     2   0.802982         9120.0   
2                                     0   0.121876         2600.0   
3                                     1   0.085113         3042.0   
4                                     0   0.036050         3300.0   
5                                     1   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
1                               13                        0   
2                                4                        0   
3                                2                        1   
4                                5                        0   
5                                7                        0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
1                             6                                     0   
2                             0                                     0   
3                             0                                     0   
4                             0                                     0   
5                             1                                     0   

   NumberOfDependents  
1                 2.0  
2                 1.0  
3                 0.0  
4                 0.0  
5                 0.0

In [53]:
df = df.dropna()
X = df.as_matrix(columns=df.columns[1:])
y = df.as_matrix(columns=df.columns[:1])
print(X.shape, y.shape)
y = y.reshape(y.shape[0])
print(X.shape, y.shape)
gkf = KFold(n_splits=5, shuffle=True)

(120269, 10) (120269, 1)
(120269, 10) (120269,)


In [20]:
for train, test in gkf.split(X, y):
    print(train.shape, test.shape)
    X_train, y_train = X[train], y[train]
    X_test, y_test = X[test], y[test]
    
#     clf.fit(X_train, y_train)
    
#     print(accuracy_score(y_pred=clf.predict(X_test), y_true=y_test))

(96215,) (24054,)
(96215,) (24054,)
(96215,) (24054,)
(96215,) (24054,)
(96216,) (24053,)


In [71]:
X


array([[  0.76612661,  45.        ,   2.        , ...,   6.        ,
          0.        ,   2.        ],
       [  0.95715102,  40.        ,   0.        , ...,   0.        ,
          0.        ,   1.        ],
       [  0.65818014,  38.        ,   1.        , ...,   0.        ,
          0.        ,   0.        ],
       ..., 
       [  0.29974515,  44.        ,   0.        , ...,   1.        ,
          0.        ,   2.        ],
       [  0.        ,  30.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.85028295,  64.        ,   0.        , ...,   2.        ,
          0.        ,   0.        ]])

In [72]:
def init_list_of_objects(size):
    list_of_objects = list()
    for i in range(0, size):
        list_of_objects.append(list())
    return list_of_objects

treeList = init_list_of_objects(pow(2, X.shape[1] + 1) - 1)
sizeArr = np.zeros((X.shape[1] + 1, 2))
print(len(treeList))

treeList[0] = np.where(y > y.min() - 1)
sizeArr[0] = treeList[0][0].shape[0]/treeList[0][0].shape[0]
print(treeList[0][0].shape[0], sizeArr[0], treeList[0])

mask = y[treeList[0][0]] > 0
treeList[1] = np.where(mask)
sizeArr[1][0] = treeList[1][0].shape[0]/treeList[0][0].shape[0]
sizeArr[1][1] = treeList[1][0].shape[0]/treeList[0][0].shape[0]
print(treeList[1][0].shape[0], sizeArr[1], treeList[1])

treeList[2] = np.where(~mask)
sizeArr[2][0] = treeList[2][0].shape[0]/treeList[0][0].shape[0]
sizeArr[2][1] = treeList[2][0].shape[0]/treeList[0][0].shape[0]
print(treeList[2][0].shape[0], sizeArr[2], treeList[2])

2047
120269 [ 1.  1.] (array([     0,      1,      2, ..., 120266, 120267, 120268]),)
8357 [ 0.0694859  0.0694859] (array([     0,     11,     18, ..., 120239, 120243, 120251]),)
111912 [ 0.9305141  0.9305141] (array([     1,      2,      3, ..., 120266, 120267, 120268]),)


In [9]:
import time

# def get_H(X):
newR = X.T[0]
ar_H1H2G = np.zeros((X.T[0].shape[0], 3))
t1 = time.time()
for el in range(len(newR)):
    beta = newR[el]
    if beta != 0:
        p1 = (beta > newR).sum() / newR.shape[0]
        p2 = (beta <= newR).sum() / newR.shape[0]
        ar_H1H2G[el][2] = -pow(p1,2)*np.log(p1) - pow(p2,2)*np.log(p2)
    else:
        ar_H1H2G[el][2] = 5
print("%.3fsec" % (time.time() - t1))
print(ar_H1H2G)
print(ar_H1H2G.T[2].min(), ar_H1H2G.T[2].argmin())

38.331sec
[[ 0.          0.          0.18899463]
 [ 0.          0.          0.1163038 ]
 [ 0.          0.          0.22367837]
 ..., 
 [ 0.          0.          0.33049682]
 [ 0.          0.          5.        ]
 [ 0.          0.          0.16054783]]
8.31539955433e-06 68523


In [5]:
import time

newR = X.T[0]
ar_H1H2G = np.zeros((newR.shape[0], ))
t1 = time.time()
for el in range(len(newR)):
    beta1 = ((np.array([newR.shape[0], ])*newR[el] - newR) > 0).sum()
    if (beta1 != 0) and (beta1 != newR.shape[0]):
        p1 = beta1 / newR.shape[0]
        # p2 = 1 - p1
        ar_H1H2G[el] = -pow(p1, 2)*np.log(p1) - pow(1 - p1, 2)*np.log(1 - p1)
    else:
        ar_H1H2G[el] = 5
print("%.3fsec" % (time.time() - t1))
print(ar_H1H2G)
print(ar_H1H2G.min(), ar_H1H2G.argmin())

28.194sec
[  5.00000000e+00   5.00000000e+00   5.00000000e+00 ...,   8.31539955e-06
   5.00000000e+00   5.00000000e+00]
8.31539955433e-06 22


In [54]:
newR = np.sort(X.T[0])
print(newR, X.T[0].min(), X.T[0].max())

[     0.      0.      0. ...,  22000.  29110.  50708.] 0.0 50708.0


In [54]:
l = 0
r = newR.shape[0] - 1
while r - l > 0:
    m = (l + r) // 2
    bm = newR[m]
    pm = np.logical_and(y > 0, X.T[0] > bm).sum() / newR.shape[0]
    gm = -pow(pm,2)*np.log(pm) - pow(1 - pm,2)*np.log(1 - pm) 
    bl = newR[r]
    pr = np.logical_and(y > 0, X.T[0] > br).sum() / newR.shape[0]
    gr = -pow(pr,2)*np.log(pr) - pow(1 - pr,2)*np.log(1 - pr) 
print("---------------------------")
print("m=", m, "newR[m]=", newR[m])
print("r=", r, "newR[r]=", newR[r])
print("pm=", pm, "gm=", gm)
print("pr=", pr, "gr=", gr)
print(gm + gr)

120269
m= 60134 newR[m]= 0.177282104
p1= 0.0584855615329 h1= 0.00971088815729
p2= 0.941514438467 h2= 0.0534224031661
0.0631332913233


In [106]:
l = 0
r = newR.shape[0] - 1
lenno = newR.shape[0]
while r - l > 1:
    m = (l + r) // 2
    bm = newR[m]
    pm1 = ((y > 0)*(X.T[0] > bm)).sum() / lenno
    pm2 = ((y > 0)*(X.T[0] <= bm)).sum() / lenno
    if pm != 0:
        gm = -pow(pm, 2)*np.log(pm) - pow((1 - pm), 2)*np.log(1 - pm) 
        br = newR[r]
        pr = ((y > 0)*(X.T[0] > br)).sum() / lenno
        if pr != 0:
            gr = -pow(pr, 2)*np.log(pr) - pow((1 - pr), 2)*np.log(1 - pr) 
            if gm < gr:
                r = m
            else:
                l = m
#             print("---------------------------")
#             print("m=", m, "newR[m]=", newR[m])
#             print("r=", r, "newR[r]=", newR[r])
#             print("pm=", pm, "gm=", gm)
#             print("pr=", pr, "gr=", gr)
            print(gm + gr)
        else:
            r = r - 1
#             print("r0!", pr, r)    
    else:
        m = m - 1
#         print("m0!", pm, m)

0.0631507663926
0.0481246449844
0.0302812011753
0.0088466115928
0.0088466115928
0.00652171871647
0.00317636478457
0.00119630955826
0.00034162314135
7.48688751111e-05
5.82244873723e-05
2.49474169727e-05
1.66307991087e-05
1.66307991087e-05
1.66307991087e-05
1.66307991087e-05
1.66307991087e-05


In [82]:
ll = 0
rr = newR.shape[0] - 1
l = ll
r = rr
Xlen = newR.shape[0]
beta = 0
iterio = 0
min_g = 2
g = np.zeros((2,))
while 1:
# while r - l > 1:
    iterio += 1
    m0 = (l + r) // 2
    m1 = m0 + (r - m0) // 2
    print(iterio, l, m0, m1, r)
    
    bm0 = newR[m0]
    bm1 = newR[m1]
    
    x0l_len = m0 - ll
    x0r_len = rr - m0
    
    x1l_len = m1 - ll
    x1r_len = rr - m1
#     print("_len", x0l_len, x0r_len, x1l_len, x1r_len)
    
    p00l = ((y > beta)*(newR <= bm0)).sum() / x0l_len
    p00r = ((y > beta)*(newR > bm0)).sum() / x0r_len    
    p10l = ((y <= beta)*(newR <= bm0)).sum() / x0l_len
    p10r = ((y <= beta)*(newR > bm0)).sum() / x0r_len
    
    
    p01l = ((y > beta)*(newR <= bm1)).sum() / x1l_len
    p01r = ((y > beta)*(newR > bm1)).sum() / x1r_len    
    p11l = ((y <= beta)*(newR <= bm1)).sum() / x1l_len
    p11r = ((y <= beta)*(newR > bm1)).sum() / x1r_len
    
    
    p0l = ((y > beta)*(newR > newR[l])*(newR <= bm0)).sum() / x0l_len
    p0r = ((y > beta)*(newR > bm0)*(newR < newR[r])).sum() / x0r_len
    p1l = ((y <= beta)*(newR > newR[l])*(newR <= bm0)).sum() / x0l_len    
    p1r = ((y <= beta)*(newR > bm0)*(newR < newR[r])).sum() / x0r_len

        
#     p01l = ((y > beta)*((newR > bm0)*(newR <= bm1))).sum() / x1l_len
#     p01r = ((y > beta)*(newR > bm1)*(newR < newR[r])).sum() / x1r_len    
#     p11l = ((y <= beta)*((newR > bm0)*(newR <= bm1))).sum() / x1l_len    
#     p11r = ((y <= beta)*(newR > bm1)*(newR < newR[r])).sum() / x1r_len

#     print("lek", ((y > beta)*(newR <= bm0)).sum(), ((y <= beta)*(newR <= bm0)).sum(), 
#                   ((y > beta)*(newR > bm0)).sum(), ((y <= beta)*(newR > bm0)).sum())
#     print("осн доли", '%.5f' % p00l, '%.5f' % p10l, '%.5f' % p00r, '%.5f' % p10r)
#     print("доп доли", '%.5f' % p01l, '%.5f' % p11l, '%.5f' % p01r, '%.5f' % p11r)
    
    hl = p00l*p10l
    hr = p00r*p10r
    h1l = p01l*p11l
    h1r = p01r*p11r
    
#     hl = -p0l*np.log(p0l) - p1l*np.log(p1l)
#     hr = -p0r*np.log(p0r) - p1r*np.log(p1r)
    g[0] = (x0l_len/Xlen)*hl + (x0r_len/Xlen)*hr    
#     h1l = -p01l*np.log(p01l) - p11l*np.log(p11l)
#     h1r = -p01r*np.log(p01r) - p11r*np.log(p11r)
    g[1] = (x1l_len/Xlen)*h1l + (x1r_len/Xlen)*h1r    

    if g0 < g1:
        r = m0
    else:
        l = m0
    
    if min_g - g.min() > pow(10, -10):
        min_g = g.min()
    else:
        print(g.argmin(), m0, m1)
        break
    print(min_g - g.min(), g0, g1)
    print("--------------")

1 0 60134 90201 120268
0.0 0.0646572651675 0.0662323316602
--------------
2 0 30067 45100 60134
0.0 0.0646572651675 0.0662323316602
--------------
3 0 15033 22550 30067
0.0 0.0646572651675 0.0662323316602
--------------
4 0 7516 11274 15033
0.0 0.0646572651675 0.0662323316602
--------------
5 0 3758 5637 7516
1 3758 5637
