# Decision tree и Random forest

Реализовать 2 класса DecisionTreeClassifier и RandomForestClassifier

In [1]:
class DecisionTreeClassifier():
    def __init__(self):
        pass
    def fit(self):
        pass
    def predict(self):
        pass
    def fit_predict(self):
        pass

In [2]:
class RandomForestClassifier():
    def __init__(self):
        pass
    def fit(self):
        pass
    def predict(self):
        pass
    def fit_predict(self):
        pass

In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold


%matplotlib inline
df = pd.read_csv('./data/cs-training.csv', sep=',')
df.head()

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
1                 1                              0.766127   45   
2                 0                              0.957151   40   
3                 0                              0.658180   38   
4                 0                              0.233810   30   
5                 0                              0.907239   49   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
1                                     2   0.802982         9120.0   
2                                     0   0.121876         2600.0   
3                                     1   0.085113         3042.0   
4                                     0   0.036050         3300.0   
5                                     1   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
1                               13                        0   
2                                4                        0   
3                                2                        1   
4                                5                        0   
5                                7                        0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
1                             6                                     0   
2                             0                                     0   
3                             0                                     0   
4                             0                                     0   
5                             1                                     0   

   NumberOfDependents  
1                 2.0  
2                 1.0  
3                 0.0  
4                 0.0  
5                 0.0

In [80]:
df = df.dropna()
X = df.as_matrix(columns=df.columns[1:])
y = df.as_matrix(columns=df.columns[:1])
print(X.shape, y.shape)
y = y.reshape(y.shape[0])
print(X.shape, y.shape)
gkf = KFold(n_splits=5, shuffle=True)

(120269, 10) (120269, 1)
(120269, 10) (120269,)


In [20]:
for train, test in gkf.split(X, y):
    print(train.shape, test.shape)
    X_train, y_train = X[train], y[train]
    X_test, y_test = X[test], y[test]
    
#     clf.fit(X_train, y_train)
    
#     print(accuracy_score(y_pred=clf.predict(X_test), y_true=y_test))

(96215,) (24054,)
(96215,) (24054,)
(96215,) (24054,)
(96215,) (24054,)
(96216,) (24053,)


In [71]:
X


array([[  0.76612661,  45.        ,   2.        , ...,   6.        ,
          0.        ,   2.        ],
       [  0.95715102,  40.        ,   0.        , ...,   0.        ,
          0.        ,   1.        ],
       [  0.65818014,  38.        ,   1.        , ...,   0.        ,
          0.        ,   0.        ],
       ..., 
       [  0.29974515,  44.        ,   0.        , ...,   1.        ,
          0.        ,   2.        ],
       [  0.        ,  30.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.85028295,  64.        ,   0.        , ...,   2.        ,
          0.        ,   0.        ]])

In [72]:
def init_list_of_objects(size):
    list_of_objects = list()
    for i in range(0, size):
        list_of_objects.append(list())
    return list_of_objects

treeList = init_list_of_objects(pow(2, X.shape[1] + 1) - 1)
sizeArr = np.zeros((X.shape[1] + 1, 2))
print(len(treeList))

treeList[0] = np.where(y > y.min() - 1)
sizeArr[0] = treeList[0][0].shape[0]/treeList[0][0].shape[0]
print(treeList[0][0].shape[0], sizeArr[0], treeList[0])

mask = y[treeList[0][0]] > 0
treeList[1] = np.where(mask)
sizeArr[1][0] = treeList[1][0].shape[0]/treeList[0][0].shape[0]
sizeArr[1][1] = treeList[1][0].shape[0]/treeList[0][0].shape[0]
print(treeList[1][0].shape[0], sizeArr[1], treeList[1])

treeList[2] = np.where(~mask)
sizeArr[2][0] = treeList[2][0].shape[0]/treeList[0][0].shape[0]
sizeArr[2][1] = treeList[2][0].shape[0]/treeList[0][0].shape[0]
print(treeList[2][0].shape[0], sizeArr[2], treeList[2])

2047
120269 [ 1.  1.] (array([     0,      1,      2, ..., 120266, 120267, 120268]),)
8357 [ 0.0694859  0.0694859] (array([     0,     11,     18, ..., 120239, 120243, 120251]),)
111912 [ 0.9305141  0.9305141] (array([     1,      2,      3, ..., 120266, 120267, 120268]),)


In [185]:
import time

def get_H(X):
    newR = X.T[0]
    ar_H1H2G = np.zeros((X.T[0].shape[0], 3))
    for el in range(len(newR)):
        beta = newR[el]
        if beta != 0:
#         mask = beta > newR
#         mask2 = beta <= newR
            p1 = (beta > newR).sum() / newR.shape[0]
            p2 = (beta <= newR).sum() / newR.shape[0]
            ar_H1H2G[el][0] = -p1*np.log(p1)
            ar_H1H2G[el][1] = -p2*np.log(p2)
            ar_H1H2G[el][2] = p1*ar_H1H2G[el][0] + p2*ar_H1H2G[el][1]
    print(ar_H1H2G)
    print(ar_H1H2G.T[2].min(), ar_H1H2G.T[2].argmin())
#     newRR = np.where(mask)
#     print(newRR)
#     print(mask.sum(), mask2.sum())

t1 = time.time()
get_H(X)
print("%.3fsec" % (time.time() - t1))

[[ 0.16272697  0.30866122  0.18899463]
 [ 0.10145195  0.23968265  0.1163038 ]
 [ 0.19311083  0.33263519  0.22367837]
 ..., 
 [ 0.3064848   0.3665181   0.33049682]
 [ 0.          0.          0.        ]
 [ 0.13851456  0.28496753  0.16054783]]
0.0 31
37.873sec


In [182]:
ar_H1H2G = np.random.randint(0, 255, (4, 5))

In [184]:
print(ar_H1H2G)
print(ar_H1H2G.T[2].min(), ar_H1H2G.T[2].argmin())

[[140  70 118 162  83]
 [187  20 213  13  39]
 [ 56  28 107  76 130]
 [ 74 149 216 104 174]]
107 2
