# Multilayer perceptron

Реализовать MLP

In [8]:
import time
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

In [ ]:
class MLP():
    def __init__(self):
        pass
    def fit(self):
        pass
    def predict(self):
        pass
    def fit_predict(self):
        pass

In [3]:
mndata = MNIST('./data')
training = mndata.load_training()
testing = mndata.load_testing()

In [54]:
a = np.array([[1],[3], [11]])
b = np.array([[0.5],[2], [3]])
c = np.array([1, 2, 3])
c.sum()

6

In [56]:
def sigmoid_activation(x):
    return 1.0 / (1 + np.exp(-x))

In [93]:
np.random.seed(5)
x = np.ones((170, 64))
w2 = np.random.random((64, 3))
w3 = np.random.random((3, 1))
d3 = np.zeros((170, 3))
# g2 = x*d3

# print(g2.shape)

h3 = x.dot(w2)
out = h3.dot(w3)
print(d3.shape)
print(h3.shape)
print(out.shape)

(170, 3)
(170, 3)
(170, 1)


In [72]:
((1-h3)*h3)*(w3*out.T)

ValueError: operands could not be broadcast together with shapes (170,3) (3,170) 

In [95]:
np.multiply(w3, out[:, np.newaxis])

array([[[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.6

In [99]:
w3*out[:, np.newaxis]

array([[[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.66993509],
        [ 17.98540408]],

       [[ 29.8332729 ],
        [ 30.6

In [98]:
out

array([[ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50.69374615],
       [ 50