In [1]:
import numpy as np

In [58]:
A = np.array([[0, 1, 14]])
A[:,:2]

array([[0, 1]])

In [9]:
A = np.vstack([A, [14, 88]])
A

array([[ 0,  1],
       [ 0,  2],
       [14, 88]])

In [11]:
A.reshape((-1, 1, 2))
A.shape

(3, 2)

In [79]:
x1 = np.zeros((10, 12))
x = 1
y = 5
h = 3
w = 4
x1[y:y+h:,x:x+w] += 1
# x1[:,:2]
x1

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [100]:
argsofmax = np.argwhere(x1 == x1.max()).mean(0, dtype=np.uint32)
print(argsofmax)


[ 6.   2.5]


In [98]:
hand_crd = np.zeros((1, 2))
print(hand_crd)
hand_crd = np.delete(hand_crd, 0, 0)
print(hand_crd)

[[ 0.  0.]]
[]


In [99]:
hand_crd = np.vstack([hand_crd, [14, 87]])
print(hand_crd)

[[ 14.  87.]]


In [101]:
maxIntensity = 255
psi = 1
teta = 1

hiimage =(maxIntensity/psi)*(gray/(maxIntensity/teta))**0.5
gray = np.array(hiimage, dtype=np.uint8)
detects = haar_cascade.detectMultiScale(gray, scaleFactor=1.05, minNeighbors=4,
                                        minSize=(d_default // 1, d_default // 1))
